### ISSUE TITLE
建议增加申请微软API的入口

### ISSUE THREAD

**Issue by shunz** [silver-ymz/bob-plugin-microsoft-translate#1]
建议增加申请微软API的入口，微软产品线又多又乱，我目前找了一圈还没找到 😓

**Comment by silver-ymz** [comment]
在`README.md`中增加了详情页和文档网址。其实，原来`READEME.md`第二行微软二字是到官网的链接。申请API，需要先注册Azure账号。

**Comment by shunz** [comment]
> 在`README.md`中增加了详情页和文档网址。其实，原来`READEME.md`第二行微软二字是到官网的链接。申请API，需要先注册Azure账号。

Thanks Bro.
